{"uuid": "90c9fdf6-6bcd-432a-b5d8-08e0a8547d4d", "children": ["e952088e-de03-4ab0-bf66-92e3e6e488e7"], "befores": [{"name": "demo_page", "status": "failed", "statusDetails": {"message": "Failed: Fixture \"demo_page\" called directly. Fixtures are not meant to be called directly,\nbut are created automatically when test functions request them as parameters.\nSee https://docs.pytest.org/en/stable/fixture.html for more information about fixtures, and\nhttps://docs.pytest.org/en/stable/deprecations.html#calling-fixtures-directly about how to update your code.\n", "trace": "  File \"D:\\Sonu\\personal\\xeneta-test\\python-page-object\\venv\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"D:\\Sonu\\personal\\xeneta-test\\python-page-object\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 1117, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"D:\\Sonu\\personal\\xeneta-test\\python-page-object\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 924, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"D:\\Sonu\\personal\\xeneta-test\\python-page-object\\tests\\plugins\\pages.py\", line 20, in demo_page\n    return demo_page(browser)\n  File \"D:\\Sonu\\personal\\xeneta-test\\python-page-object\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 1166, in result\n    fail(message, pytrace=False)\n  File \"D:\\Sonu\\personal\\xeneta-test\\python-page-object\\venv\\lib\\site-packages\\_pytest\\outcomes.py\", line 156, in fail\n    raise Failed(msg=msg, pytrace=pytrace)\n"}, "start": 1617593346210, "stop": 1617593346211}], "start": 1617593346210, "stop": 1617593346258}