{"uuid": "c0522f5f-ff6b-46df-9e21-b0220557cd41", "children": ["69744b6c-8476-44df-b1b9-b3aed23a0bae"], "befores": [{"name": "demo_page", "status": "failed", "statusDetails": {"message": "Failed: Fixture \"demo_page\" called directly. Fixtures are not meant to be called directly,\nbut are created automatically when test functions request them as parameters.\nSee https://docs.pytest.org/en/stable/fixture.html for more information about fixtures, and\nhttps://docs.pytest.org/en/stable/deprecations.html#calling-fixtures-directly about how to update your code.\n", "trace": "  File \"D:\\Sonu\\personal\\xeneta-test\\python-page-object\\venv\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"D:\\Sonu\\personal\\xeneta-test\\python-page-object\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 1117, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"D:\\Sonu\\personal\\xeneta-test\\python-page-object\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 924, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"D:\\Sonu\\personal\\xeneta-test\\python-page-object\\tests\\plugins\\pages.py\", line 20, in demo_page\n    return demo_page(browser)\n  File \"D:\\Sonu\\personal\\xeneta-test\\python-page-object\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 1166, in result\n    fail(message, pytrace=False)\n  File \"D:\\Sonu\\personal\\xeneta-test\\python-page-object\\venv\\lib\\site-packages\\_pytest\\outcomes.py\", line 156, in fail\n    raise Failed(msg=msg, pytrace=pytrace)\n"}, "start": 1617593332477, "stop": 1617593332478}], "start": 1617593332477, "stop": 1617593332527}